-- ═══════════════════════════════════════════════════════════════
-- SREE ELECTRICALS & ELECTRONICS — Complete Database Setup
-- Run this ONCE in MySQL Workbench on your CleverCloud database
-- Safe to re-run: all INSERTs use INSERT IGNORE
-- ═══════════════════════════════════════════════════════════════

USE bgkwzqnaueygs0sltdxg;

-- ─── TABLES ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id       INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS settings (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  gst_value DECIMAL(5,2) NOT NULL DEFAULT 18.00
);

CREATE TABLE IF NOT EXISTS products (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  section   VARCHAR(100)  NOT NULL,
  product   VARCHAR(255)  NOT NULL,
  brand     VARCHAR(100)  NOT NULL,
  spec      VARCHAR(255)  DEFAULT '',
  unit      VARCHAR(100)  DEFAULT '',
  price     DECIMAL(10,2) NOT NULL DEFAULT 0,
  warranty  VARCHAR(50)   DEFAULT '',
  guarantee VARCHAR(50)   DEFAULT '',
  INDEX idx_product (product),
  INDEX idx_section (section),
  INDEX idx_brand   (brand)
);

CREATE TABLE IF NOT EXISTS bill_history (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  bill_no        VARCHAR(50)   NOT NULL,
  customer_name  VARCHAR(255),
  customer_phone VARCHAR(15),
  items_json     TEXT,
  grand_total    DECIMAL(10,2),
  bill_datetime  VARCHAR(50),
  created_by     VARCHAR(100),
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_phone (customer_phone),
  INDEX idx_name  (customer_name)
);

CREATE TABLE IF NOT EXISTS bill_counter (
  bill_date VARCHAR(8) PRIMARY KEY,
  counter   INT NOT NULL DEFAULT 0
);

-- ─── USERS ───────────────────────────────────────────────────────────

INSERT IGNORE INTO users (username, password) VALUES ('admin',  'admin123');
INSERT IGNORE INTO users (username, password) VALUES ('Seeni',  'Seeni@1969');
INSERT IGNORE INTO users (username, password) VALUES ('Ari',    'Ari@1999');
INSERT IGNORE INTO users (username, password) VALUES ('Arul',   'Arul@2001');
INSERT IGNORE INTO users (username, password) VALUES ('Ashok',  'Ashok@2002');

-- Remove old test user if exists
DELETE FROM users WHERE username = 'john';

-- ─── SETTINGS ────────────────────────────────────────────────────────

INSERT INTO settings (gst_value)
SELECT 18.00 WHERE NOT EXISTS (SELECT 1 FROM settings);

-- ─── PRODUCTS (422 items from Excel price catalog) ────────────────────
-- section  = product category sheet
-- product  = item name
-- brand    = manufacturer/company
-- spec     = specification type
-- unit     = pack unit (Per piece / 90 mtr coil / etc.)
-- price    = rate in ₹

INSERT IGNORE INTO products (section, product, brand, spec, unit, price) VALUES
  ('Wires & Cables', '0.5 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 210.0),
  ('Wires & Cables', '0.5 sq mm Wire', 'Havells', 'Single Core FRLS', '90 mtr coil', 245.0),
  ('Wires & Cables', '0.75 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 295.0),
  ('Wires & Cables', '0.75 sq mm Wire', 'Polycab', 'Single Core FR', '90 mtr coil', 310.0),
  ('Wires & Cables', '1.0 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 385.0),
  ('Wires & Cables', '1.0 sq mm Wire', 'Havells', 'Single Core FRLS', '90 mtr coil', 420.0),
  ('Wires & Cables', '1.5 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 550.0),
  ('Wires & Cables', '1.5 sq mm Wire', 'Polycab', 'Single Core FR', '90 mtr coil', 580.0),
  ('Wires & Cables', '1.5 sq mm Wire', 'Havells', 'Single Core FRLS', '90 mtr coil', 610.0),
  ('Wires & Cables', '2.5 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 870.0),
  ('Wires & Cables', '2.5 sq mm Wire', 'Polycab', 'Single Core FR', '90 mtr coil', 895.0),
  ('Wires & Cables', '2.5 sq mm Wire', 'Havells', 'Single Core FRLS', '90 mtr coil', 940.0),
  ('Wires & Cables', '4.0 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 1380.0),
  ('Wires & Cables', '4.0 sq mm Wire', 'Polycab', 'Single Core FR', '90 mtr coil', 1420.0),
  ('Wires & Cables', '6.0 sq mm Wire', 'Finolex', 'Single Core FR', '90 mtr coil', 2050.0),
  ('Wires & Cables', '6.0 sq mm Wire', 'Havells', 'Single Core FRLS', '90 mtr coil', 2180.0),
  ('Wires & Cables', '10 sq mm Wire', 'Finolex', 'Single Core FR', 'Per metre', 38.0),
  ('Wires & Cables', '16 sq mm Wire', 'Polycab', 'Single Core FR', 'Per metre', 58.0),
  ('Wires & Cables', '25 sq mm Wire', 'Finolex', 'Single Core FR', 'Per metre', 88.0),
  ('Wires & Cables', '35 sq mm Wire', 'Polycab', 'Single Core FR', 'Per metre', 120.0),
  ('Wires & Cables', '2 Core 0.5 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 12.0),
  ('Wires & Cables', '2 Core 0.75 sq mm Flex', 'Polycab', 'Round Flexible', 'Per metre', 16.0),
  ('Wires & Cables', '2 Core 1.0 sq mm Flex', 'Havells', 'Round Flexible', 'Per metre', 21.0),
  ('Wires & Cables', '2 Core 1.5 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 28.0),
  ('Wires & Cables', '2 Core 2.5 sq mm Flex', 'Polycab', 'Round Flexible', 'Per metre', 42.0),
  ('Wires & Cables', '3 Core 1.0 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 30.0),
  ('Wires & Cables', '3 Core 1.5 sq mm Flex', 'Havells', 'Round Flexible', 'Per metre', 42.0),
  ('Wires & Cables', '3 Core 2.5 sq mm Flex', 'Polycab', 'Round Flexible', 'Per metre', 65.0),
  ('Wires & Cables', '3 Core 4.0 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 98.0),
  ('Wires & Cables', '3 Core 6.0 sq mm Flex', 'Polycab', 'Round Flexible', 'Per metre', 145.0),
  ('Wires & Cables', '4 Core 1.0 sq mm Flex', 'Havells', 'Round Flexible', 'Per metre', 38.0),
  ('Wires & Cables', '4 Core 1.5 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 52.0),
  ('Wires & Cables', '4 Core 2.5 sq mm Flex', 'Polycab', 'Round Flexible', 'Per metre', 80.0),
  ('Wires & Cables', '5 Core 1.5 sq mm Flex', 'Havells', 'Round Flexible', 'Per metre', 65.0),
  ('Wires & Cables', '5 Core 2.5 sq mm Flex', 'Finolex', 'Round Flexible', 'Per metre', 98.0),
  ('Wires & Cables', '2 Core 4 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 145.0),
  ('Wires & Cables', '2 Core 6 sq mm Armoured', 'Finolex', 'SWA Armoured', 'Per metre', 198.0),
  ('Wires & Cables', '3.5 Core 10 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 285.0),
  ('Wires & Cables', '3.5 Core 16 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 420.0),
  ('Wires & Cables', '3.5 Core 25 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 620.0),
  ('Wires & Cables', '3.5 Core 35 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 850.0),
  ('Wires & Cables', '3.5 Core 50 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 1150.0),
  ('Wires & Cables', '3.5 Core 70 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 1550.0),
  ('Wires & Cables', '3.5 Core 95 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 2050.0),
  ('Wires & Cables', '3.5 Core 120 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 2650.0),
  ('Wires & Cables', '3.5 Core 150 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 3250.0),
  ('Wires & Cables', '3.5 Core 185 sq mm Armoured', 'Polycab', 'SWA Armoured', 'Per metre', 4100.0),
  ('Wires & Cables', '3.5 Core 240 sq mm Armoured', 'KEI', 'SWA Armoured', 'Per metre', 5200.0),
  ('Wires & Cables', 'RG6 Coaxial Cable', 'Finolex', 'CCTV/TV Cable', 'Per metre', 18.0),
  ('Wires & Cables', 'RG11 Coaxial Cable', 'Polycab', 'CCTV/TV Cable', 'Per metre', 35.0),
  ('Wires & Cables', 'CAT5e LAN Cable', 'D-Link', 'UTP 4 Pair', '305 mtr box', 3800.0),
  ('Wires & Cables', 'CAT6 LAN Cable', 'D-Link', 'UTP 4 Pair', '305 mtr box', 5200.0),
  ('Wires & Cables', 'CAT6A LAN Cable', 'Polycab', 'UTP 4 Pair', '305 mtr box', 8500.0),
  ('Wires & Cables', 'Telephone Cable 2 Pair', 'Finolex', 'CW1308', 'Per metre', 8.0),
  ('Wires & Cables', 'Telephone Cable 4 Pair', 'Finolex', 'CW1308', 'Per metre', 14.0),
  ('Wires & Cables', 'Speaker Cable 2 Core', 'Anchor', '100/200V', 'Per metre', 22.0),
  ('Wires & Cables', 'HDMI Cable 1.5m', 'Belkin', '4K 18Gbps', 'Per piece', 650.0),
  ('Wires & Cables', 'HDMI Cable 3m', 'Belkin', '4K 18Gbps', 'Per piece', 950.0),
  ('Wires & Cables', 'Alarm Cable 4 Core', 'Finolex', 'Security', 'Per metre', 12.0),
  ('Switches & Sockets', '1 Way Switch 6A', 'Anchor Roma', 'Modular White', 'Per piece', 28.0),
  ('Switches & Sockets', '1 Way Switch 6A', 'Legrand Lyncus', 'Modular White', 'Per piece', 95.0),
  ('Switches & Sockets', '1 Way Switch 6A', 'Havells Crabtree', 'Modular', 'Per piece', 78.0),
  ('Switches & Sockets', '1 Way Switch 6A', 'Schneider', 'Modular', 'Per piece', 110.0),
  ('Switches & Sockets', '2 Way Switch 6A', 'Anchor Roma', 'Modular White', 'Per piece', 38.0),
  ('Switches & Sockets', '2 Way Switch 6A', 'Legrand Lyncus', 'Modular White', 'Per piece', 115.0),
  ('Switches & Sockets', '2 Way Switch 6A', 'Havells Crabtree', 'Modular', 'Per piece', 95.0),
  ('Switches & Sockets', 'Bell Push 6A', 'Anchor Roma', 'Modular', 'Per piece', 22.0),
  ('Switches & Sockets', 'Bell Push 6A', 'Legrand Lyncus', 'Modular', 'Per piece', 75.0),
  ('Switches & Sockets', 'Fan Regulator 5 Step', 'Anchor Roma', 'Electronic', 'Per piece', 145.0),
  ('Switches & Sockets', 'Fan Regulator 5 Step', 'Havells', 'Electronic', 'Per piece', 285.0),
  ('Switches & Sockets', 'Dimmer Switch 500W', 'Legrand', 'Modular', 'Per piece', 395.0),
  ('Switches & Sockets', 'Dimmer Switch 500W', 'Schneider', 'Modular', 'Per piece', 425.0),
  ('Switches & Sockets', '5A 2 Pin Socket', 'Anchor Roma', 'Modular', 'Per piece', 22.0),
  ('Switches & Sockets', '5A 2 Pin Socket', 'Legrand', 'Modular', 'Per piece', 65.0),
  ('Switches & Sockets', '6A 3 Pin Socket', 'Anchor Roma', 'Modular', 'Per piece', 32.0),
  ('Switches & Sockets', '6A 3 Pin Socket', 'Legrand Lyncus', 'Modular', 'Per piece', 85.0),
  ('Switches & Sockets', '6A 3 Pin Socket', 'Havells Crabtree', 'Modular', 'Per piece', 75.0),
  ('Switches & Sockets', '16A 3 Pin Socket', 'Anchor Roma', 'Modular (AC/Geyser)', 'Per piece', 58.0),
  ('Switches & Sockets', '16A 3 Pin Socket', 'Legrand', 'Modular (AC/Geyser)', 'Per piece', 145.0),
  ('Switches & Sockets', '16A 3 Pin Socket', 'Havells', 'Modular (AC/Geyser)', 'Per piece', 125.0),
  ('Switches & Sockets', '32A 3 Pin Socket', 'Legrand', 'Modular (High Load)', 'Per piece', 245.0),
  ('Switches & Sockets', 'USB Socket 2.4A', 'Anchor', 'USB A+A', 'Per piece', 285.0),
  ('Switches & Sockets', 'USB Socket Type C', 'Legrand', 'USB A+C 3A', 'Per piece', 395.0),
  ('Switches & Sockets', 'Universal Socket', 'Anchor Roma', 'Multi-pin', 'Per piece', 45.0),
  ('Switches & Sockets', 'Extension Board 4 Socket', 'Anchor', '6A with Switch', 'Per piece', 285.0),
  ('Switches & Sockets', 'Extension Board 6 Socket', 'Belkin', '6A with USB', 'Per piece', 895.0),
  ('Switches & Sockets', 'Extension Board Surge', 'APC', 'Surge Protector', 'Per piece', 1250.0),
  ('Switches & Sockets', '1M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 18.0),
  ('Switches & Sockets', '2M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 25.0),
  ('Switches & Sockets', '3M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 32.0),
  ('Switches & Sockets', '4M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 38.0),
  ('Switches & Sockets', '6M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 48.0),
  ('Switches & Sockets', '8M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 62.0),
  ('Switches & Sockets', '12M Modular Plate', 'Anchor Roma', 'White', 'Per piece', 85.0),
  ('Switches & Sockets', '1M Plate Legrand', 'Legrand Lyncus', 'White', 'Per piece', 55.0),
  ('Switches & Sockets', '2M Plate Legrand', 'Legrand Lyncus', 'White', 'Per piece', 75.0),
  ('Switches & Sockets', '3M Plate Legrand', 'Legrand Lyncus', 'White', 'Per piece', 98.0),
  ('Switches & Sockets', '6M Plate Legrand', 'Legrand Lyncus', 'White', 'Per piece', 145.0),
  ('Switches & Sockets', 'Flush Box 1M', 'Anchor', 'MS Box', 'Per piece', 22.0),
  ('Switches & Sockets', 'Flush Box 2M', 'Anchor', 'MS Box', 'Per piece', 28.0),
  ('Switches & Sockets', 'Flush Box 3M', 'Anchor', 'MS Box', 'Per piece', 35.0),
  ('Switches & Sockets', 'Industrial Socket 16A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 485.0),
  ('Switches & Sockets', 'Industrial Socket 32A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 695.0),
  ('Switches & Sockets', 'Industrial Socket 63A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 1250.0),
  ('Switches & Sockets', 'Industrial Plug 16A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 285.0),
  ('Switches & Sockets', 'Industrial Plug 32A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 395.0),
  ('Switches & Sockets', 'Industrial Plug 63A 3P', 'Legrand', 'IP44 CEE', 'Per piece', 750.0),
  ('Switches & Sockets', 'Isolator Switch 32A DP', 'Havells', 'Surface Mount', 'Per piece', 385.0),
  ('Switches & Sockets', 'Isolator Switch 63A DP', 'Havells', 'Surface Mount', 'Per piece', 650.0),
  ('Switches & Sockets', 'Isolator Switch 100A TP', 'L&T', 'Surface Mount', 'Per piece', 1450.0),
  ('Lighting', '3W LED Bulb', 'Philips', 'Cool White 6500K', 'Per piece', 65.0),
  ('Lighting', '5W LED Bulb', 'Philips', 'Cool/Warm White', 'Per piece', 85.0),
  ('Lighting', '5W LED Bulb', 'Havells', 'Cool/Warm White', 'Per piece', 95.0),
  ('Lighting', '7W LED Bulb', 'Philips', 'Cool/Warm White', 'Per piece', 110.0),
  ('Lighting', '7W LED Bulb', 'Syska', 'Cool/Warm White', 'Per piece', 95.0),
  ('Lighting', '9W LED Bulb', 'Philips', 'Cool/Warm White', 'Per piece', 135.0),
  ('Lighting', '9W LED Bulb', 'Havells', 'Cool/Warm White', 'Per piece', 145.0),
  ('Lighting', '12W LED Bulb', 'Philips', 'Cool/Warm White', 'Per piece', 175.0),
  ('Lighting', '12W LED Bulb', 'Wipro', 'Cool/Warm White', 'Per piece', 165.0),
  ('Lighting', '15W LED Bulb', 'Havells', 'Cool/Warm White', 'Per piece', 210.0),
  ('Lighting', '18W LED Bulb', 'Philips', 'Cool/Warm White', 'Per piece', 265.0),
  ('Lighting', '20W LED Bulb', 'Syska', 'Cool White', 'Per piece', 295.0),
  ('Lighting', '3W LED Spot', 'Philips', '3 inch Recessed', 'Per piece', 145.0),
  ('Lighting', '5W LED Panel Round', 'Havells', '4 inch Recessed', 'Per piece', 185.0),
  ('Lighting', '9W LED Panel Round', 'Philips', '4 inch Recessed', 'Per piece', 225.0),
  ('Lighting', '12W LED Panel Round', 'Wipro', '5 inch Recessed', 'Per piece', 285.0),
  ('Lighting', '15W LED Panel Square', 'Philips', '6x6 inch', 'Per piece', 350.0),
  ('Lighting', '18W LED Panel Square', 'Havells', '6x6 inch', 'Per piece', 420.0),
  ('Lighting', '24W LED Panel Square', 'Wipro', '8x8 inch', 'Per piece', 585.0),
  ('Lighting', '36W LED Panel', 'Philips', '600x600mm', 'Per piece', 1250.0),
  ('Lighting', '40W LED Panel', 'Havells', '600x600mm', 'Per piece', 1350.0),
  ('Lighting', '48W LED Panel', 'Wipro', '600x600mm', 'Per piece', 1650.0),
  ('Lighting', '10W LED Batten 2ft', 'Philips', '4000K Neutral', 'Per piece', 180.0),
  ('Lighting', '10W LED Batten 2ft', 'Havells', '6500K Cool', 'Per piece', 195.0),
  ('Lighting', '18W LED Batten 4ft', 'Philips', '4000K Neutral', 'Per piece', 280.0),
  ('Lighting', '18W LED Batten 4ft', 'Havells', '6500K Cool', 'Per piece', 295.0),
  ('Lighting', '18W LED Batten 4ft', 'Syska', '6500K Cool', 'Per piece', 245.0),
  ('Lighting', '20W LED Batten 4ft', 'Wipro', '6500K Cool', 'Per piece', 310.0),
  ('Lighting', '22W LED Batten 5ft', 'Philips', '6500K Cool', 'Per piece', 395.0),
  ('Lighting', '36W LED Batten 4ft', 'Havells', '6500K Cool', 'Per piece', 520.0),
  ('Lighting', '40W LED Batten 4ft', 'Philips', '6500K Cool', 'Per piece', 580.0),
  ('Lighting', '20W LED Flood Light', 'Havells', 'IP65 Outdoor', 'Per piece', 1250.0),
  ('Lighting', '30W LED Flood Light', 'Philips', 'IP65 Outdoor', 'Per piece', 1650.0),
  ('Lighting', '50W LED Flood Light', 'Havells', 'IP65 Outdoor', 'Per piece', 2450.0),
  ('Lighting', '100W LED Flood Light', 'Wipro', 'IP65 Outdoor', 'Per piece', 4500.0),
  ('Lighting', '150W LED Flood Light', 'Philips', 'IP65 Outdoor', 'Per piece', 6500.0),
  ('Lighting', '30W LED Street Light', 'Wipro', 'IP65 AC', 'Per piece', 2800.0),
  ('Lighting', '45W LED Street Light', 'Havells', 'IP65 AC', 'Per piece', 3950.0),
  ('Lighting', '60W LED Street Light', 'Philips', 'IP65 AC', 'Per piece', 5200.0),
  ('Lighting', '80W LED Street Light', 'Wipro', 'IP65 AC', 'Per piece', 6800.0),
  ('Lighting', '12W LED Garden Light', 'Wipro', 'IP44 Spike', 'Per piece', 850.0),
  ('Lighting', 'LED Strip 5050 RGB', 'Syska', '12V 5mtr IP20', 'Per roll', 650.0),
  ('Lighting', 'LED Strip 5050 WW', 'Philips', '12V 5mtr IP20', 'Per roll', 550.0),
  ('Lighting', 'LED Strip 2835 CW', 'Havells', '24V 5mtr', 'Per roll', 480.0),
  ('Lighting', 'LED Strip IP65 WW', 'Syska', '12V 5mtr Waterproof', 'Per roll', 850.0),
  ('Lighting', 'Neon Flex Red', 'Generic', '12V IP65 5mtr', 'Per roll', 950.0),
  ('Lighting', 'Neon Flex Blue', 'Generic', '12V IP65 5mtr', 'Per roll', 950.0),
  ('Lighting', 'Neon Flex RGB', 'Syska', '12V IP65 5mtr', 'Per roll', 1650.0),
  ('Lighting', 'LED Driver 12V 10W', 'Anchor', 'SMPS', 'Per piece', 185.0),
  ('Lighting', 'LED Driver 12V 30W', 'Anchor', 'SMPS', 'Per piece', 345.0),
  ('Lighting', 'LED Driver 24V 60W', 'Havells', 'SMPS', 'Per piece', 685.0),
  ('Lighting', 'LED Driver 12V 100W', 'Generic', 'SMPS', 'Per piece', 850.0),
  ('MCB & DB Boards', 'MCB 6A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 165.0),
  ('MCB & DB Boards', 'MCB 10A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 165.0),
  ('MCB & DB Boards', 'MCB 16A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 165.0),
  ('MCB & DB Boards', 'MCB 20A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 175.0),
  ('MCB & DB Boards', 'MCB 25A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 185.0),
  ('MCB & DB Boards', 'MCB 32A 1P Type B', 'Legrand', '4.5kA', 'Per piece', 195.0),
  ('MCB & DB Boards', 'MCB 40A 1P Type C', 'Legrand', '6kA', 'Per piece', 245.0),
  ('MCB & DB Boards', 'MCB 63A 1P Type C', 'Legrand', '6kA', 'Per piece', 345.0),
  ('MCB & DB Boards', 'MCB 6A 1P', 'Havells', '4.5kA', 'Per piece', 145.0),
  ('MCB & DB Boards', 'MCB 16A 1P', 'Havells', '4.5kA', 'Per piece', 145.0),
  ('MCB & DB Boards', 'MCB 32A 1P', 'Havells', '4.5kA', 'Per piece', 175.0),
  ('MCB & DB Boards', 'MCB 63A 1P', 'Havells', '4.5kA', 'Per piece', 295.0),
  ('MCB & DB Boards', 'MCB 16A 2P', 'L&T', '4.5kA Double Pole', 'Per piece', 385.0),
  ('MCB & DB Boards', 'MCB 32A 2P', 'L&T', '4.5kA Double Pole', 'Per piece', 450.0),
  ('MCB & DB Boards', 'MCB 63A 2P', 'Legrand', '6kA Double Pole', 'Per piece', 685.0),
  ('MCB & DB Boards', 'MCB 16A 3P', 'Legrand', '4.5kA Triple Pole', 'Per piece', 545.0),
  ('MCB & DB Boards', 'MCB 32A 3P', 'Havells', '4.5kA Triple Pole', 'Per piece', 650.0),
  ('MCB & DB Boards', 'MCB 63A 3P', 'L&T', '6kA Triple Pole', 'Per piece', 985.0),
  ('MCB & DB Boards', 'MCB 100A 3P', 'Legrand', '10kA Triple Pole', 'Per piece', 1850.0),
  ('MCB & DB Boards', 'MCB 125A 3P', 'Havells', '10kA Triple Pole', 'Per piece', 2250.0),
  ('MCB & DB Boards', 'RCCB 25A 2P 30mA', 'Legrand', 'Type AC', 'Per piece', 850.0),
  ('MCB & DB Boards', 'RCCB 40A 2P 30mA', 'Legrand', 'Type AC', 'Per piece', 995.0),
  ('MCB & DB Boards', 'RCCB 63A 2P 30mA', 'Havells', 'Type AC', 'Per piece', 1150.0),
  ('MCB & DB Boards', 'RCCB 100A 2P 30mA', 'L&T', 'Type AC', 'Per piece', 1850.0),
  ('MCB & DB Boards', 'RCCB 25A 4P 30mA', 'Legrand', 'Type AC 4 Pole', 'Per piece', 1650.0),
  ('MCB & DB Boards', 'RCCB 40A 4P 30mA', 'Havells', 'Type AC 4 Pole', 'Per piece', 1950.0),
  ('MCB & DB Boards', 'RCCB 63A 4P 30mA', 'L&T', 'Type AC 4 Pole', 'Per piece', 2450.0),
  ('MCB & DB Boards', 'RCCB 100A 4P 30mA', 'Legrand', 'Type AC 4 Pole', 'Per piece', 3250.0),
  ('MCB & DB Boards', 'RCBO 16A 1P+N 30mA', 'Legrand', 'Combined MCB+RCCB', 'Per piece', 1250.0),
  ('MCB & DB Boards', 'RCBO 32A 1P+N 30mA', 'Legrand', 'Combined MCB+RCCB', 'Per piece', 1450.0),
  ('MCB & DB Boards', '4 Way SPN DB', 'Legrand', 'Surface/Flush', 'Per piece', 1250.0),
  ('MCB & DB Boards', '6 Way SPN DB', 'Legrand', 'Surface/Flush', 'Per piece', 1550.0),
  ('MCB & DB Boards', '8 Way SPN DB', 'Havells', 'Surface/Flush', 'Per piece', 1850.0),
  ('MCB & DB Boards', '10 Way SPN DB', 'L&T', 'Surface/Flush', 'Per piece', 2250.0),
  ('MCB & DB Boards', '12 Way SPN DB', 'Legrand', 'Surface/Flush', 'Per piece', 2650.0),
  ('MCB & DB Boards', '16 Way SPN DB', 'Havells', 'Surface/Flush', 'Per piece', 3250.0),
  ('MCB & DB Boards', '4 Way TPN DB', 'Legrand', 'Triple Pole+N', 'Per piece', 2850.0),
  ('MCB & DB Boards', '8 Way TPN DB', 'L&T', 'Triple Pole+N', 'Per piece', 4500.0),
  ('MCB & DB Boards', '12 Way TPN DB', 'Legrand', 'Triple Pole+N', 'Per piece', 6500.0),
  ('MCB & DB Boards', '16 Way TPN DB', 'Havells', 'Triple Pole+N', 'Per piece', 8500.0),
  ('MCB & DB Boards', 'Busbar 3P 63A', 'Legrand', 'For 12 ways MCB', 'Per piece', 850.0),
  ('MCB & DB Boards', 'Busbar 3P 100A', 'L&T', 'For 12 ways MCB', 'Per piece', 1250.0),
  ('MCB & DB Boards', 'Neutral Link 12 Way', 'Anchor', 'Painted', 'Per piece', 185.0),
  ('MCB & DB Boards', 'Earth Link 12 Way', 'Anchor', 'Painted', 'Per piece', 185.0),
  ('MCB & DB Boards', 'MCCB 100A 3P', 'Schneider', '16kA Compact NSX', 'Per piece', 8500.0),
  ('MCB & DB Boards', 'MCCB 160A 3P', 'Schneider', '25kA Compact NSX', 'Per piece', 14500.0),
  ('MCB & DB Boards', 'MCCB 250A 3P', 'L&T', '25kA', 'Per piece', 22000.0),
  ('MCB & DB Boards', 'MCCB 400A 3P', 'L&T', '35kA', 'Per piece', 38000.0),
  ('MCB & DB Boards', 'MCCB 630A 3P', 'Schneider', '50kA', 'Per piece', 65000.0),
  ('MCB & DB Boards', 'ACB 800A 3P', 'Legrand', '65kA Draw Out', 'Per piece', 125000.0),
  ('MCB & DB Boards', 'ACB 1250A 3P', 'Legrand', '65kA Draw Out', 'Per piece', 185000.0),
  ('Conduits & Pipes', 'PVC Pipe 16mm (0.5")', 'Precision', 'Light Duty Class B', '3mtr piece', 28.0),
  ('Conduits & Pipes', 'PVC Pipe 20mm (0.75")', 'Precision', 'Light Duty Class B', '3mtr piece', 35.0),
  ('Conduits & Pipes', 'PVC Pipe 25mm (1")', 'Precision', 'Light Duty Class B', '3mtr piece', 48.0),
  ('Conduits & Pipes', 'PVC Pipe 32mm (1.25")', 'Precision', 'Light Duty Class B', '3mtr piece', 65.0),
  ('Conduits & Pipes', 'PVC Pipe 40mm (1.5")', 'Precision', 'Light Duty Class B', '3mtr piece', 85.0),
  ('Conduits & Pipes', 'PVC Pipe 50mm (2")', 'Precision', 'Light Duty Class B', '3mtr piece', 125.0),
  ('Conduits & Pipes', 'PVC Pipe 16mm (0.5")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 45.0),
  ('Conduits & Pipes', 'PVC Pipe 20mm (0.75")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 58.0),
  ('Conduits & Pipes', 'PVC Pipe 25mm (1")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 78.0),
  ('Conduits & Pipes', 'PVC Pipe 32mm (1.25")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 105.0),
  ('Conduits & Pipes', 'PVC Pipe 40mm (1.5")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 138.0),
  ('Conduits & Pipes', 'PVC Pipe 50mm (2")', 'Astral', 'Heavy Duty Class D', '3mtr piece', 198.0),
  ('Conduits & Pipes', 'PVC Pipe 63mm (2.5")', 'Precision', 'Heavy Duty', '3mtr piece', 265.0),
  ('Conduits & Pipes', 'PVC Pipe 75mm (3")', 'Astral', 'Heavy Duty', '3mtr piece', 365.0),
  ('Conduits & Pipes', 'PVC Pipe 110mm (4")', 'Precision', 'Heavy Duty', '3mtr piece', 550.0),
  ('Conduits & Pipes', 'GI Conduit 20mm (0.75")', 'Steelco', 'Light Gauge 1.2mm', '3mtr piece', 185.0),
  ('Conduits & Pipes', 'GI Conduit 25mm (1")', 'Steelco', 'Light Gauge 1.2mm', '3mtr piece', 245.0),
  ('Conduits & Pipes', 'GI Conduit 32mm (1.25")', 'Steelco', 'Light Gauge 1.2mm', '3mtr piece', 325.0),
  ('Conduits & Pipes', 'GI Conduit 40mm (1.5")', 'Steelco', 'Heavy Gauge 1.6mm', '3mtr piece', 485.0),
  ('Conduits & Pipes', 'GI Conduit 50mm (2")', 'Steelco', 'Heavy Gauge 1.6mm', '3mtr piece', 650.0),
  ('Conduits & Pipes', 'GI Conduit 63mm (2.5")', 'Steelco', 'Heavy Gauge 1.6mm', '3mtr piece', 850.0),
  ('Conduits & Pipes', 'GI Conduit 75mm (3")', 'Steelco', 'Heavy Gauge 2.0mm', '3mtr piece', 1150.0),
  ('Conduits & Pipes', 'GI Conduit 100mm (4")', 'Steelco', 'Heavy Gauge 2.0mm', '3mtr piece', 1650.0),
  ('Conduits & Pipes', 'Flexible Conduit 16mm', 'Precision', 'PVC Corrugated', 'Per metre', 12.0),
  ('Conduits & Pipes', 'Flexible Conduit 20mm', 'Precision', 'PVC Corrugated', 'Per metre', 15.0),
  ('Conduits & Pipes', 'Flexible Conduit 25mm', 'Precision', 'PVC Corrugated', 'Per metre', 20.0),
  ('Conduits & Pipes', 'Flexible Conduit 32mm', 'Precision', 'PVC Corrugated', 'Per metre', 28.0),
  ('Conduits & Pipes', 'Metallic Flex Conduit 20mm', 'Steelco', 'Galvanized Steel', 'Per metre', 45.0),
  ('Conduits & Pipes', 'Metallic Flex Conduit 25mm', 'Steelco', 'Galvanized Steel', 'Per metre', 58.0),
  ('Conduits & Pipes', 'PVC Elbow 20mm', 'Precision', '90 Degree', 'Per piece', 8.0),
  ('Conduits & Pipes', 'PVC Elbow 25mm', 'Precision', '90 Degree', 'Per piece', 12.0),
  ('Conduits & Pipes', 'PVC Junction Box 20mm', 'Precision', '1 Entry', 'Per piece', 15.0),
  ('Conduits & Pipes', 'PVC Junction Box 25mm', 'Precision', '4 Entry', 'Per piece', 22.0),
  ('Conduits & Pipes', 'PVC Draw Box 20mm', 'Astral', 'Surface', 'Per piece', 35.0),
  ('Conduits & Pipes', 'Saddle Clamp 20mm', 'Precision', 'PVC', 'Per piece', 3.0),
  ('Conduits & Pipes', 'Saddle Clamp 25mm', 'Precision', 'PVC', 'Per piece', 4.0),
  ('Conduits & Pipes', 'Saddle Clamp 32mm', 'Precision', 'PVC', 'Per piece', 5.0),
  ('Conduits & Pipes', 'Coupler 20mm', 'Precision', 'PVC', 'Per piece', 5.0),
  ('Conduits & Pipes', 'Coupler 25mm', 'Precision', 'PVC', 'Per piece', 7.0),
  ('Conduits & Pipes', 'Coupler 32mm', 'Precision', 'PVC', 'Per piece', 9.0),
  ('Conduits & Pipes', 'Cable Tray 50x25mm', 'Legrand', 'Perforated GI', 'Per metre', 185.0),
  ('Conduits & Pipes', 'Cable Tray 100x50mm', 'Legrand', 'Perforated GI', 'Per metre', 285.0),
  ('Conduits & Pipes', 'Cable Tray 150x50mm', 'Legrand', 'Perforated GI', 'Per metre', 385.0),
  ('Conduits & Pipes', 'Cable Tray 200x50mm', 'Legrand', 'Perforated GI', 'Per metre', 520.0),
  ('Conduits & Pipes', 'Cable Tray 300x50mm', 'Legrand', 'Perforated GI', 'Per metre', 750.0),
  ('Conduits & Pipes', 'Cable Tray 450x100mm', 'Legrand', 'Perforated GI', 'Per metre', 1250.0),
  ('Conduits & Pipes', 'Cable Raceway 25x16mm', 'Legrand', 'PVC White', 'Per metre', 65.0),
  ('Conduits & Pipes', 'Cable Raceway 40x25mm', 'Legrand', 'PVC White', 'Per metre', 95.0),
  ('Conduits & Pipes', 'Cable Raceway 60x40mm', 'Legrand', 'PVC White', 'Per metre', 145.0),
  ('Conduits & Pipes', 'Cable Raceway 100x60mm', 'Legrand', 'PVC White', 'Per metre', 225.0),
  ('Conduits & Pipes', 'Mini Raceway 12x8mm', 'Legrand', 'PVC White', 'Per metre', 35.0),
  ('Conduits & Pipes', 'Cable Tie 100mm', 'Panduit', 'Nylon White', 'Pack 100', 65.0),
  ('Conduits & Pipes', 'Cable Tie 200mm', 'Panduit', 'Nylon White', 'Pack 100', 95.0),
  ('Conduits & Pipes', 'Cable Tie 300mm', 'Panduit', 'Nylon Black UV', 'Pack 100', 145.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm', 'Havells', 'Standard 70W', 'Per piece', 2250.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm', 'Bajaj', 'Standard 75W', 'Per piece', 1850.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm', 'Orient', 'Standard 70W', 'Per piece', 1950.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm', 'Usha', 'Standard 72W', 'Per piece', 2050.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm BLDC', 'Havells', 'BLDC 28W', 'Per piece', 3850.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm BLDC', 'Orient', 'BLDC 26W', 'Per piece', 3650.0),
  ('Fans & Exhaust', 'Ceiling Fan 1200mm BLDC', 'Atomberg', 'BLDC 28W', 'Per piece', 4250.0),
  ('Fans & Exhaust', 'Ceiling Fan 900mm', 'Havells', 'Small 50W', 'Per piece', 1650.0),
  ('Fans & Exhaust', 'Ceiling Fan 1400mm', 'Usha', 'Large 85W', 'Per piece', 3250.0),
  ('Fans & Exhaust', 'Ceiling Fan Decorative', 'Havells', 'Designer Model', 'Per piece', 4500.0),
  ('Fans & Exhaust', 'Exhaust Fan 6 inch', 'Havells', 'Ventilair', 'Per piece', 650.0),
  ('Fans & Exhaust', 'Exhaust Fan 6 inch', 'Bajaj', 'Freshee', 'Per piece', 545.0),
  ('Fans & Exhaust', 'Exhaust Fan 8 inch', 'Havells', 'Ventilair', 'Per piece', 850.0),
  ('Fans & Exhaust', 'Exhaust Fan 8 inch', 'Usha', 'Crisp Air', 'Per piece', 795.0),
  ('Fans & Exhaust', 'Exhaust Fan 10 inch', 'Havells', 'Ventilair', 'Per piece', 1150.0),
  ('Fans & Exhaust', 'Exhaust Fan 12 inch', 'Bajaj', 'Freshee', 'Per piece', 1450.0),
  ('Fans & Exhaust', 'Exhaust Fan 9 inch', 'Crompton', 'Brisk Air', 'Per piece', 950.0),
  ('Fans & Exhaust', 'Inline Duct Fan 4 inch', 'Vents', 'Mixed Flow', 'Per piece', 1850.0),
  ('Fans & Exhaust', 'Inline Duct Fan 6 inch', 'Vents', 'Mixed Flow', 'Per piece', 2650.0),
  ('Fans & Exhaust', 'Kitchen Hood Fan', 'Faber', 'Chimney 60cm', 'Per piece', 8500.0),
  ('Fans & Exhaust', 'Table Fan 400mm', 'Bajaj', 'Ultima', 'Per piece', 1450.0),
  ('Fans & Exhaust', 'Table Fan 400mm', 'Orient', 'Tornado', 'Per piece', 1350.0),
  ('Fans & Exhaust', 'Pedestal Fan 450mm', 'Bajaj', 'Esteem', 'Per piece', 2250.0),
  ('Fans & Exhaust', 'Pedestal Fan 450mm', 'Havells', 'Swing ZX', 'Per piece', 2650.0),
  ('Fans & Exhaust', 'Wall Fan 400mm', 'Usha', 'Helix', 'Per piece', 1850.0),
  ('Fans & Exhaust', 'Wall Fan 450mm', 'Bajaj', 'Ultima', 'Per piece', 2150.0),
  ('Fans & Exhaust', 'Tower Fan 40 inch', 'Philips', '3 Speed', 'Per piece', 5500.0),
  ('Fans & Exhaust', 'Tower Fan 42 inch', 'Orient', 'Tornado', 'Per piece', 6500.0),
  ('Switches & Protection', 'Stabilizer 500VA TV', 'V-Guard', 'Digi 200', 'Per piece', 1250.0),
  ('Switches & Protection', 'Stabilizer 1KVA', 'V-Guard', 'Crystal Plus', 'Per piece', 2250.0),
  ('Switches & Protection', 'Stabilizer 2KVA', 'V-Guard', 'Crystal Plus', 'Per piece', 3250.0),
  ('Switches & Protection', 'Stabilizer 3KVA', 'Microtek', 'EM4160', 'Per piece', 4500.0),
  ('Switches & Protection', 'Stabilizer 4KVA', 'V-Guard', 'Digi 400', 'Per piece', 5800.0),
  ('Switches & Protection', 'Stabilizer 5KVA', 'Microtek', 'Digital', 'Per piece', 7500.0),
  ('Switches & Protection', 'Stabilizer 7.5KVA', 'V-Guard', '3Ph Input', 'Per piece', 12500.0),
  ('Switches & Protection', 'Stabilizer 10KVA', 'Microtek', '3Ph Input', 'Per piece', 16500.0),
  ('Switches & Protection', 'Stabilizer 15KVA', 'V-Guard', '3Ph Output', 'Per piece', 24500.0),
  ('Switches & Protection', 'AC Stabilizer 1.5T', 'V-Guard', 'AI1250', 'Per piece', 4500.0),
  ('Switches & Protection', 'AC Stabilizer 2T', 'Microtek', 'Digital', 'Per piece', 5800.0),
  ('Switches & Protection', 'UPS 600VA Home', 'APC', 'Back-UPS BX', 'Per piece', 3250.0),
  ('Switches & Protection', 'UPS 1KVA Home', 'APC', 'Back-UPS BX', 'Per piece', 5500.0),
  ('Switches & Protection', 'UPS 2KVA Home', 'APC', 'Smart-UPS', 'Per piece', 12500.0),
  ('Switches & Protection', 'UPS 1KVA 3Ph', 'Microtek', 'Online UPS', 'Per piece', 22000.0),
  ('Switches & Protection', 'Inverter 850VA', 'Luminous', 'Eco Volt Neo', 'Per piece', 3850.0),
  ('Switches & Protection', 'Inverter 1500VA', 'Luminous', 'Cruze', 'Per piece', 6500.0),
  ('Switches & Protection', 'Inverter 2000VA', 'Microtek', 'Super Power', 'Per piece', 9500.0),
  ('Switches & Protection', 'Inverter 3500VA', 'Luminous', 'Pro Series', 'Per piece', 18500.0),
  ('Switches & Protection', 'Solar Inverter 1KW', 'Luminous', 'MPPT', 'Per piece', 12500.0),
  ('Switches & Protection', 'Solar Inverter 5KW', 'SolarEdge', 'HD Wave', 'Per piece', 85000.0),
  ('Switches & Protection', 'Battery 12V 7Ah', 'Exide', 'VRLA Sealed', 'Per piece', 1250.0),
  ('Switches & Protection', 'Battery 12V 26Ah', 'Amaron', 'VRLA Sealed', 'Per piece', 3500.0),
  ('Switches & Protection', 'Battery 12V 42Ah', 'Exide', 'Tubular Flat', 'Per piece', 5800.0),
  ('Switches & Protection', 'Battery 12V 100Ah Flat', 'Luminous', 'Flat Plate', 'Per piece', 9500.0),
  ('Switches & Protection', 'Battery 12V 100Ah Tubular', 'Exide', 'Tall Tubular', 'Per piece', 11500.0),
  ('Switches & Protection', 'Battery 12V 150Ah Tubular', 'Amaron', 'Tall Tubular', 'Per piece', 16500.0),
  ('Switches & Protection', 'Battery 12V 200Ah Tubular', 'Luminous', 'Tall Tubular', 'Per piece', 22000.0),
  ('Accessories & Tools', 'Wire Connector 1.5-4mm', 'Wago', 'Push-in 3 way', 'Per piece', 18.0),
  ('Accessories & Tools', 'Wire Connector 2.5-6mm', 'Wago', 'Push-in 2 way', 'Per piece', 22.0),
  ('Accessories & Tools', 'Crimping Terminal 1.5mm', 'Bootlace', 'Copper Ferrule', 'Pack 100', 85.0),
  ('Accessories & Tools', 'Crimping Terminal 2.5mm', 'Bootlace', 'Copper Ferrule', 'Pack 100', 110.0),
  ('Accessories & Tools', 'Crimping Terminal 4mm', 'Bootlace', 'Copper Ferrule', 'Pack 100', 145.0),
  ('Accessories & Tools', 'Insulation Tape Black', '3M', 'Scotch 33+', 'Per roll', 45.0),
  ('Accessories & Tools', 'Insulation Tape Red', '3M', 'Scotch 33+', 'Per roll', 45.0),
  ('Accessories & Tools', 'Self Amalgamating Tape', '3M', '2228 Mastic', 'Per roll', 285.0),
  ('Accessories & Tools', 'Cable Lug 10mm Cu', 'Dowell', 'Ring Type', 'Per piece', 15.0),
  ('Accessories & Tools', 'Cable Lug 25mm Cu', 'Dowell', 'Ring Type', 'Per piece', 28.0),
  ('Accessories & Tools', 'Cable Lug 50mm Cu', 'Dowell', 'Ring Type', 'Per piece', 55.0),
  ('Accessories & Tools', 'Cable Lug 70mm Cu', 'Dowell', 'Ring Type', 'Per piece', 75.0),
  ('Accessories & Tools', 'Cable Lug 95mm Cu', 'Dowell', 'Ring Type', 'Per piece', 105.0),
  ('Accessories & Tools', 'Cable Lug 120mm Cu', 'Dowell', 'Ring Type', 'Per piece', 145.0),
  ('Accessories & Tools', 'Jointing Kit LT MV', 'Raychem', 'Heat Shrink', 'Per kit', 850.0),
  ('Accessories & Tools', 'Earth Pit GI 40x40mm', 'Ennee', 'GI Strip 3mtr', 'Per piece', 1850.0),
  ('Accessories & Tools', 'Earth Pit Cu Plate', 'Ennee', '600x600x3mm', 'Per piece', 4500.0),
  ('Accessories & Tools', 'Earth Electrode Cu Bond', 'Ennee', '3mtr x 17.2mm', 'Per piece', 3250.0),
  ('Accessories & Tools', 'Earth Rod GI 1.5mtr', 'Ennee', '17.2mm dia', 'Per piece', 850.0),
  ('Accessories & Tools', 'Earth Strip GI 25x3mm', 'Ennee', 'ISI', 'Per metre', 85.0),
  ('Accessories & Tools', 'Earth Strip Cu 25x3mm', 'Ennee', 'ISI', 'Per metre', 350.0),
  ('Accessories & Tools', 'Earthing Compound', 'Ennee', 'Gel-X', 'Per kg', 195.0),
  ('Accessories & Tools', 'Lightning Arrester', 'Ennee', 'ESE Type', 'Per piece', 18500.0),
  ('Accessories & Tools', 'Surge Arrester 230V', 'Legrand', 'Type 2 SPD', 'Per piece', 2850.0),
  ('Accessories & Tools', 'Surge Arrester 400V 3P', 'Legrand', 'Type 2 SPD', 'Per piece', 5500.0),
  ('Accessories & Tools', 'Screwdriver Set 6pc', 'Stanley', 'Insulated VDE', 'Per set', 650.0),
  ('Accessories & Tools', 'Pliers Combination 8"', 'Stanley', 'VDE 1000V', 'Per piece', 385.0),
  ('Accessories & Tools', 'Wire Stripper', 'Knipex', 'Auto Strip', 'Per piece', 1250.0),
  ('Accessories & Tools', 'Crimping Tool Ratchet', 'Knipex', 'For Lugs', 'Per piece', 1850.0),
  ('Accessories & Tools', 'Cable Cutter 16mm', 'Knipex', 'For Cu/Al', 'Per piece', 985.0),
  ('Accessories & Tools', 'Cable Cutter 50mm', 'Knipex', 'Heavy Duty', 'Per piece', 2850.0),
  ('Accessories & Tools', 'Voltage Tester Pen', 'Fluke', 'Digital Non-Contact', 'Per piece', 1450.0),
  ('Accessories & Tools', 'Multimeter Digital', 'Fluke', '117 True RMS', 'Per piece', 8500.0),
  ('Accessories & Tools', 'Clamp Meter', 'Fluke', '376 FC', 'Per piece', 18500.0),
  ('Accessories & Tools', 'Insulation Tester 1000V', 'Fluke', '1587FC', 'Per piece', 35000.0),
  ('Accessories & Tools', 'Earth Tester', 'Kyoritsu', 'KEW4105A', 'Per piece', 22000.0),
  ('Accessories & Tools', 'Drill Machine 13mm', 'Bosch', 'GSB 550W', 'Per piece', 3250.0),
  ('Accessories & Tools', 'Drill Machine 13mm Cord', 'Bosch', 'GSB 750W', 'Per piece', 4500.0),
  ('Accessories & Tools', 'Angle Grinder 4.5"', 'Bosch', 'GWS 850C', 'Per piece', 2850.0),
  ('Accessories & Tools', 'Hacksaw Frame', 'Stanley', 'Adjustable', 'Per piece', 285.0),
  ('Accessories & Tools', 'Fish Tape 15mtr', 'Ideal', 'Steel', 'Per piece', 1250.0),
  ('Accessories & Tools', 'Pipe Bender Manual', 'Generic', 'For GI 20-25mm', 'Per piece', 1850.0),
  ('Electronics & Automation', 'Smart Switch 2 Gang', 'Anchor', 'WiFi App Control', 'Per piece', 1850.0),
  ('Electronics & Automation', 'Smart Switch 4 Gang', 'Legrand', 'WiFi App Control', 'Per piece', 2850.0),
  ('Electronics & Automation', 'Smart Dimmer Switch', 'Havells', 'WiFi App Control', 'Per piece', 2250.0),
  ('Electronics & Automation', 'Smart Plug 16A', 'Anchor', 'WiFi Energy Monitor', 'Per piece', 1250.0),
  ('Electronics & Automation', 'Smart Fan Controller', 'Atomberg', 'BLDC Fan Module', 'Per piece', 1650.0),
  ('Electronics & Automation', 'Motion Sensor PIR', 'Legrand', '360 Degree Ceiling', 'Per piece', 850.0),
  ('Electronics & Automation', 'Motion Sensor Wall', 'Schneider', '120 Degree', 'Per piece', 650.0),
  ('Electronics & Automation', 'Photoelectric Sensor', 'Legrand', 'LDR Dusk-Dawn', 'Per piece', 485.0),
  ('Electronics & Automation', 'Timer Switch Digital', 'Havells', '24H Programmable', 'Per piece', 650.0),
  ('Electronics & Automation', 'Timer Switch Weekly', 'Legrand', '7 Day Program', 'Per piece', 1250.0),
  ('Electronics & Automation', 'Smart Hub Zigbee', 'Philips Hue', 'Bridge v2', 'Per piece', 4500.0),
  ('Electronics & Automation', 'Voice Control Module', 'Amazon', 'Echo Dot 5th Gen', 'Per piece', 4499.0),
  ('Electronics & Automation', 'CCTV Camera 2MP Bullet', 'CP Plus', 'HD IR 30m', 'Per piece', 1250.0),
  ('Electronics & Automation', 'CCTV Camera 4MP Dome', 'Hikvision', 'IR 30m IP66', 'Per piece', 2850.0),
  ('Electronics & Automation', 'CCTV Camera 8MP 4K', 'Dahua', 'Ultra HD IR 40m', 'Per piece', 5500.0),
  ('Electronics & Automation', 'IP Camera 4MP', 'Hikvision', 'PoE Indoor', 'Per piece', 3850.0),
  ('Electronics & Automation', 'PTZ Camera 2MP', 'CP Plus', '20X Optical Zoom', 'Per piece', 22000.0),
  ('Electronics & Automation', 'DVR 4Ch 1080P', 'CP Plus', 'H.265+ SATA', 'Per piece', 2850.0),
  ('Electronics & Automation', 'DVR 8Ch 1080P', 'Hikvision', 'H.265+ 2 SATA', 'Per piece', 4500.0),
  ('Electronics & Automation', 'NVR 8Ch 4K', 'Dahua', 'PoE NVR H.265', 'Per piece', 7500.0),
  ('Electronics & Automation', 'HDD 1TB Surveillance', 'WD Purple', 'CMR 5400 RPM', 'Per piece', 3250.0),
  ('Electronics & Automation', 'HDD 2TB Surveillance', 'Seagate SkyHawk', 'CMR', 'Per piece', 5500.0),
  ('Electronics & Automation', 'Video Door Phone', 'CP Plus', '2MP WiFi Bell', 'Per piece', 5500.0),
  ('Electronics & Automation', 'Video Door Phone', 'Hikvision', 'IP HD Camera Bell', 'Per piece', 7500.0),
  ('Electronics & Automation', 'Access Control Biometric', 'ZKTeco', 'Fingerprint+Card', 'Per piece', 8500.0),
  ('Electronics & Automation', 'Electric Door Lock', 'ZKTeco', 'Electromagnetic', 'Per piece', 3250.0),
  ('Electronics & Automation', 'WiFi Router Dual Band', 'TP-Link', 'AC1200', 'Per piece', 2250.0),
  ('Electronics & Automation', 'WiFi Router Tri Band', 'TP-Link', 'Deco Mesh', 'Per piece', 6500.0),
  ('Electronics & Automation', 'Network Switch 8 Port', 'TP-Link', 'PoE Gigabit', 'Per piece', 3250.0),
  ('Electronics & Automation', 'Network Switch 16 Port', 'D-Link', 'Gigabit Unmanaged', 'Per piece', 4500.0),
  ('Electronics & Automation', 'Network Switch 24 Port', 'D-Link', 'Gigabit Managed', 'Per piece', 12500.0),
  ('Electronics & Automation', 'PoE Switch 8 Port', 'TP-Link', '802.3af/at 65W', 'Per piece', 5500.0),
  ('Electronics & Automation', 'OFC Patch Panel 24P', 'Molex', 'LC Duplex SM', 'Per piece', 8500.0),
  ('Electronics & Automation', 'RJ45 Keystone Cat6', 'Panduit', 'UTP Unshielded', 'Per piece', 85.0),
  ('Electronics & Automation', 'RJ45 Plug Cat6', 'Panduit', 'Gold Plated Pack 50', 'Per piece', 450.0),
  ('Electronics & Automation', 'Patch Cord Cat6 1m', 'D-Link', 'UTP LSZH', 'Per piece', 185.0),
  ('Electronics & Automation', 'Patch Cord Cat6 2m', 'D-Link', 'UTP LSZH', 'Per piece', 225.0),
  ('Electronics & Automation', 'Patch Cord Cat6 3m', 'D-Link', 'UTP LSZH', 'Per piece', 265.0),
  ('Electronics & Automation', 'Fiber Optic Pigtail LC', 'Generic', 'SM 9/125', 'Per piece', 85.0),
  ('Electronics & Automation', 'Media Converter', 'D-Link', '100Mbps FE SFP', 'Per piece', 1850.0),
  ('Electronics & Automation', 'Contactor 9A 3P', 'Siemens', '3RT AC Coil', 'Per piece', 850.0),
  ('Electronics & Automation', 'Contactor 18A 3P', 'L&T', 'MNX Series', 'Per piece', 1250.0),
  ('Electronics & Automation', 'Contactor 32A 3P', 'Siemens', '3RT AC Coil', 'Per piece', 1850.0),
  ('Electronics & Automation', 'Contactor 63A 3P', 'L&T', 'MNX Series', 'Per piece', 3250.0),
  ('Electronics & Automation', 'Overload Relay 1-4A', 'Siemens', '3RU Bimetallic', 'Per piece', 650.0),
  ('Electronics & Automation', 'Overload Relay 4-13A', 'L&T', 'MN Series', 'Per piece', 850.0),
  ('Electronics & Automation', 'Overload Relay 10-40A', 'Siemens', '3RU Bimetallic', 'Per piece', 1250.0),
  ('Electronics & Automation', 'Star Delta Starter 5HP', 'L&T', 'Automatic', 'Per piece', 5500.0),
  ('Electronics & Automation', 'Star Delta Starter 10HP', 'Siemens', 'Automatic', 'Per piece', 8500.0),
  ('Electronics & Automation', 'DOL Starter 3HP', 'L&T', 'Direct Online', 'Per piece', 2250.0),
  ('Electronics & Automation', 'Soft Starter 5HP', 'Schneider', 'ATS22', 'Per piece', 12500.0),
  ('Electronics & Automation', 'VFD 1HP', 'Schneider', 'ATV310', 'Per piece', 8500.0),
  ('Electronics & Automation', 'VFD 5HP', 'ABB', 'ACH550', 'Per piece', 22000.0),
  ('Electronics & Automation', 'VFD 10HP', 'Siemens', 'G120', 'Per piece', 42000.0),
  ('Electronics & Automation', 'Relay 230V DPDT', 'Omron', 'MY2N', 'Per piece', 285.0),
  ('Electronics & Automation', 'Timer Relay 8 Pin', 'Omron', 'H3Y', 'Per piece', 450.0),
  ('Electronics & Automation', 'PLC Micro 8I/8O', 'Siemens', 'LOGO 24V', 'Per piece', 12500.0);


-- ─── VERIFY ──────────────────────────────────────────────────────────

SELECT 'users'        AS tbl, COUNT(*) AS rows FROM users
UNION ALL
SELECT 'settings'     AS tbl, COUNT(*) AS rows FROM settings
UNION ALL
SELECT 'products'     AS tbl, COUNT(*) AS rows FROM products
UNION ALL
SELECT 'bill_history' AS tbl, COUNT(*) AS rows FROM bill_history
UNION ALL
SELECT 'bill_counter' AS tbl, COUNT(*) AS rows FROM bill_counter;

-- Expected: users=5, settings=1, products=422, bill_history=0, bill_counter=0
